#pragma once

enum LED_SHAPE
{
	LED_SHAPE_LINE = 0,
	LED_SHAPE_CIRCLE = 1
};

enum LED_PATTERN_TYPE
{
	LED_PATTERN_TYPE_SOLID = 0,
	LED_PATTERN_TYPE_RAINBOW = 1,
	LED_PATTERN_TYPE_TWOTONE = 2
};

enum MessageKey
{
	MKEY_ENABLE_ALL = 1,
	MKEY_DISABLE_ALL = 2,
	MKEY_AFK = 32,
	MKEY_AWAKE = 33,
	MKEY_WIFI_CONNECTING = 34,
	MKEY_WIFI_CONNECTED = 35,
	MKEY_MQTT_CONNECTING = 36,
	MKEY_MQTT_CONNECTED = 37,
	MKEY_CONNECTED = 38,
	MKEY_CONFIG_MODE = 39,
	MKEY_OTA_BEGIN = 40,
	MKEY_OTA_END = 41,

	MKEY_LED_PATTERNS = 132,
	MKEY_LED_SEGMENTS = 164,

	MKEY_MOTOR_SPEED = 200,

	MKEY_FROM_DEVICE_STATUS = 1000,
};

/*


*/